# Generated by Django 3.1.1 on 2020-09-15 09:24

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_bool', models.BooleanField(default=False, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', verbose_name='bool')),
                ('f_nullbool', models.NullBooleanField(help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', verbose_name='nullbool')),
                ('f_small_int', models.PositiveSmallIntegerField(default=0, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', verbose_name='small int')),
                ('f_int_choices', models.PositiveSmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')], default=1, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', verbose_name='int choices')),
                ('f_int_choices2', models.PositiveSmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')], default=1, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', verbose_name='radio choices')),
                ('f_int', models.IntegerField(default=0, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', verbose_name='int')),
                ('f_bigint', models.BigIntegerField(default=0, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', verbose_name='bigint')),
                ('f_float', models.FloatField(default=0, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', verbose_name='float')),
                ('f_decimal', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', max_digits=16, verbose_name='decimal')),
                ('f_duration', models.DurationField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', null=True, verbose_name='duration')),
                ('f_date', models.DateField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', null=True, verbose_name='date')),
                ('f_date2', models.DateField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', null=True, verbose_name='date selects')),
                ('f_time', models.TimeField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', null=True, verbose_name='time')),
                ('f_datetime', models.DateTimeField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', null=True, verbose_name='datetime')),
                ('f_hidden1', models.CharField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', max_length=128, verbose_name='hidden1')),
                ('f_hidden2', models.CharField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', max_length=128, verbose_name='hidden2')),
                ('f_hidden3', models.CharField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', max_length=128, verbose_name='hidden3')),
                ('f_char', models.CharField(help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', max_length=128, verbose_name='char')),
                ('f_slug', models.SlugField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', max_length=128, verbose_name='slug')),
                ('f_email', models.EmailField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', max_length=254, verbose_name='email')),
                ('f_pass', models.CharField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', max_length=128, verbose_name='password')),
                ('f_ip', models.GenericIPAddressField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', null=True, verbose_name='IP')),
                ('f_text', models.TextField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', max_length=512, verbose_name='text')),
                ('f_url', models.URLField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', verbose_name='URL')),
                ('f_uuid', models.UUIDField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', null=True, verbose_name='UUID')),
                ('f_filepath', models.FilePathField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', path='/home/jon/Python/www/paper-admin/tests/tests', verbose_name='filepath')),
                ('f_file', models.FileField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', upload_to='category', verbose_name='file')),
                ('f_image', models.ImageField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', upload_to='category', verbose_name='image')),
                ('f_char_ro', models.CharField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', max_length=128, verbose_name='char RO')),
                ('f_int_ro', models.IntegerField(default=0, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', verbose_name='int RO')),
                ('f_text_ro', models.TextField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', verbose_name='text RO')),
                ('order', models.PositiveIntegerField(default=0, editable=False, verbose_name='order')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', max_length=128, verbose_name='name')),
                ('number', models.IntegerField(default=7, verbose_name='number')),
                ('order', models.PositiveIntegerField(default=0, editable=False, verbose_name='order')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='category')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.subcategory')),
            ],
            options={
                'verbose_name': 'subcategory',
                'verbose_name_plural': 'subcategories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.IntegerField(default=1, verbose_name='hidden')),
                ('readonly', models.CharField(blank=True, default='Do not edit me', max_length=128, verbose_name='readonly')),
                ('name', models.CharField(help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', max_length=128, verbose_name='name')),
                ('slug', models.SlugField(help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', verbose_name='slug')),
                ('url', models.URLField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', verbose_name='url')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='f_fk',
            field=models.ForeignKey(help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.tag', verbose_name='FK'),
        ),
        migrations.AddField(
            model_name='category',
            name='f_fk1',
            field=models.ForeignKey(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.tag', verbose_name='FK Autocomplete'),
        ),
        migrations.AddField(
            model_name='category',
            name='f_fk2',
            field=models.ForeignKey(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.tag', verbose_name='FK Radio'),
        ),
        migrations.AddField(
            model_name='category',
            name='f_fk3',
            field=models.ForeignKey(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.tag', verbose_name='FK Raw ID'),
        ),
        migrations.AddField(
            model_name='category',
            name='f_o2o',
            field=models.OneToOneField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.tag', verbose_name='One-to-One'),
        ),
        migrations.AddField(
            model_name='category',
            name='f_tags',
            field=models.ManyToManyField(help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', to='app.Tag', verbose_name='M2M'),
        ),
        migrations.AddField(
            model_name='category',
            name='f_tags1',
            field=models.ManyToManyField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', related_name='_category_f_tags1_+', to='app.Tag', verbose_name='M2M Checkboxes'),
        ),
        migrations.AddField(
            model_name='category',
            name='f_tags2',
            field=models.ManyToManyField(help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', related_name='_category_f_tags2_+', to='app.Tag', verbose_name='M2M Raw ID'),
        ),
        migrations.AddField(
            model_name='category',
            name='f_tags3',
            field=models.ManyToManyField(help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', related_name='_category_f_tags3_+', to='app.Tag', verbose_name='M2M Horizontal'),
        ),
        migrations.AddField(
            model_name='category',
            name='f_tags4',
            field=models.ManyToManyField(help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', related_name='_category_f_tags4_+', to='app.Tag', verbose_name='M2M Vertical'),
        ),
        migrations.AddField(
            model_name='category',
            name='f_tags5',
            field=models.ManyToManyField(help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', related_name='_category_f_tags5_+', to='app.Tag', verbose_name='M2M Autocomplete'),
        ),
    ]
