# Generated by Django 3.1.1 on 2020-09-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='f_filepath',
            field=models.FilePathField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', path='/home/jon/Python/www/paper-admin/tests/app', verbose_name='filepath'),
        ),
    ]
