# Generated by Django 2.1.15 on 2021-05-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210521_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tree',
            options={'verbose_name': 'tree', 'verbose_name_plural': 'tree'},
        ),
        migrations.RemoveField(
            model_name='tree',
            name='order',
        ),
    ]
