# Generated by Django 3.1.1 on 2020-09-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sigletonexample'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sigletonexample',
            options={'verbose_name': 'singleton', 'verbose_name_plural': 'singletons'},
        ),
        migrations.AddField(
            model_name='category',
            name='f_bool2',
            field=models.BooleanField(default=False, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', verbose_name='bool 2'),
        ),
    ]
