# Generated by Django 2.1.15 on 2021-05-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210521_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tree',
            options={'verbose_name': 'tree', 'verbose_name_plural': 'trees'},
        ),
        migrations.RemoveField(
            model_name='tree',
            name='number',
        ),
    ]
