# Generated by Django 2.1.15 on 2021-05-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210526_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='category',
        ),
    ]
