# Generated by Django 3.1.6 on 2021-02-24 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200916_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dal_fk',
            field=models.ForeignKey(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.tag', verbose_name='FK'),
        ),
        migrations.AddField(
            model_name='category',
            name='dal_m2m',
            field=models.ManyToManyField(help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', related_name='_category_dal_m2m_+', to='app.Tag', verbose_name='M2M'),
        ),
    ]
