# Generated by Django 3.2.6 on 2021-08-18 09:30

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_tree_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tree",
            new_name="MPTTTree"
        ),
    ]
