# Generated by Django 5.0 on 2023-12-07 23:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_widgets_f_money_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
