# Generated by Django 2.1.15 on 2021-05-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_item_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='age',
            field=models.IntegerField(default=18, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', verbose_name='age'),
        ),
    ]
