# Generated by Django 4.0.1 on 2022-01-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210825_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='f_nullbool',
        ),
    ]
