# Generated by Django 3.2.25 on 2024-05-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgets',
            name='f_checkbox_tree_m2m',
            field=models.ManyToManyField(blank=True, help_text='<code>ManyToManyField</code> with <code>AdminCheckboxTree</code> widget', related_name='_app_widgets_f_checkbox_tree_m2m_+', to='app.Tag', verbose_name='Checkbox Tree M2M'),
        ),
        migrations.AlterField(
            model_name='widgets',
            name='f_checkbox_m2m',
            field=models.ManyToManyField(blank=True, help_text='<code>ManyToManyField</code> with <code>AdminCheckboxSelectMultiple</code> widget', related_name='_app_widgets_f_checkbox_m2m_+', to='app.Tag', verbose_name='Checkbox M2M'),
        ),
    ]
