# Generated by Django 4.1.7 on 2023-03-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_category_f_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('failure', 'Failure')], max_length=32, verbose_name='status'),
        ),
    ]
