# Generated by Django 4.1.7 on 2023-03-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_category_status_alter_category_dal_m2m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('failure', 'Failure')], max_length=32, verbose_name='status'),
        ),
    ]
