# Generated by Django 4.1.7 on 2023-03-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_item_status_alter_category_dal_m2m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='dal_m2m',
            field=models.ManyToManyField(help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', related_name='+', to='app.tag', verbose_name='M2M'),
        ),
        migrations.AlterField(
            model_name='category',
            name='f_int_choices2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')], default=1, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', null=True, verbose_name='radio choices'),
        ),
        migrations.AlterField(
            model_name='category',
            name='f_tags1',
            field=models.ManyToManyField(blank=True, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', related_name='+', to='app.tag', verbose_name='M2M Checkboxes'),
        ),
        migrations.AlterField(
            model_name='category',
            name='f_tags2',
            field=models.ManyToManyField(help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', related_name='+', to='app.tag', verbose_name='M2M Raw ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='f_tags3',
            field=models.ManyToManyField(help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', related_name='+', to='app.tag', verbose_name='M2M Horizontal'),
        ),
        migrations.AlterField(
            model_name='category',
            name='f_tags4',
            field=models.ManyToManyField(help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', related_name='+', to='app.tag', verbose_name='M2M Vertical'),
        ),
        migrations.AlterField(
            model_name='category',
            name='f_tags5',
            field=models.ManyToManyField(help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', related_name='+', to='app.tag', verbose_name='M2M Autocomplete'),
        ),
    ]
