# Generated by Django 4.1.7 on 2023-03-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_category_dal_m2m_alter_category_f_int_choices2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='f_int_choices2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')], help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', null=True, verbose_name='radio choices'),
        ),
    ]
