# Generated by Django 4.1.7 on 2023-03-28 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_category_f_int_choices2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='f_fk',
            field=models.ForeignKey(default=1, help_text='Lorem ipsum <b>dolor</b> sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.tag', verbose_name='FK'),
            preserve_default=False,
        ),
    ]
