# Generated by Django 4.1.7 on 2023-03-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_widgets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SigletonExample',
            new_name='Sigleton',
        ),
        migrations.AlterModelOptions(
            name='sigleton',
            options={'verbose_name': 'singleton'},
        ),
        migrations.AlterField(
            model_name='widgets',
            name='f_date',
            field=models.DateField(blank=True, help_text='Standard <code>DateField</code>', null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='widgets',
            name='f_datetime',
            field=models.DateTimeField(blank=True, help_text='Standard <code>DateTimeField</code>', null=True, verbose_name='datetime'),
        ),
        migrations.AlterField(
            model_name='widgets',
            name='f_select_date',
            field=models.DateField(blank=True, help_text='<code>DateField</code> with <code>SelectDateWidget</code>', null=True, verbose_name='date selects'),
        ),
        migrations.AlterField(
            model_name='widgets',
            name='f_switch',
            field=models.BooleanField(default=False, help_text='Boolean field with <code>AdminSwitchInput</code> widget', verbose_name='switch'),
        ),
        migrations.AlterField(
            model_name='widgets',
            name='f_text',
            field=models.TextField(blank=True, help_text='Standard <code>TextField</code>', verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='widgets',
            name='f_time',
            field=models.TimeField(blank=True, help_text='Standard <code>TimeField</code>', null=True, verbose_name='time'),
        ),
    ]
