# Generated by Django 4.1.7 on 2023-03-29 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_author_book_alter_widgets_f_file_input_review_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookauthor',
            options={'ordering': ['-id'], 'verbose_name': 'Author'},
        ),
        migrations.RemoveField(
            model_name='bookauthor',
            name='order',
        ),
    ]
