# Generated by Django 4.1.7 on 2023-03-29 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_message_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
