language: python
python:
  - 3.9
  - 3.8
  - 3.7
  - 3.6
before_install:
  - nvm install 15
  - node --version
  - npm ci
  - pip install -U pip setuptools wheel tox-travis
  - pip install twine
  - pip install -r ./requirements.txt
  - npx webpack --mode=production
branches:
  only:
    - master
    - dev
    - "/^v?\\d(\\.\\d+)+$/"
script:
  - python setup.py sdist
  - python setup.py bdist_wheel
  - twine check dist/*
  - tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  user: __token__
  password:
    secure: g76hvojiGPvoO6mPoBSdfYOoFr8sHG7JCyAtVjvSBk4hcZ09GjhwkX0By7H+aLXnzjGGYUTyHSMH9NojdkoQ9AhKffydW++cEY/pbzpEJl0hDAVteQYGfT1ZK/1DOa33DIo2yyMtZyyzMnd/QfdW7Zii6MFFY2subm3sMHfcDYpiIcRSZmu82SlLJPSu5EE7sj8ZGGswsUDGq/mp0LUwNlZIE0aUWeFlnQOQRZjR1Jv1dmksW5P797gJVS1myRXdLN2uM30yr8wZbJcfuv+3xiYRY7jwyg7aiY7PYep18YwVHtMs3GzN8fMzD5mwDPgLhJAAqBrsP9xhk8pdPp0MxZGSnBLijPhI/dpoySxv1JkB+iaH96//9VmjH8SfhHv+Fk6grIvAEGs3bQO1Biqh80v/av5zh4aNiY/qZmFrQFg56HcEE8NmfA9d19QuUJ0FMzxsLo79eXgWsJg1QQMaLh5DljdQBmPvTff98QCuDkpLfA/uK1luIgLyJfOoos670ePyMTnwv+UGHtHEW4U6F6H6x6JLscOZuojli5496Um0rzQbQNdZs8KceHFcmq473FEIi33hwluDthJJIBQoY++HASSwHkqtALKiQoVGaG2onGt3WqxHaCBJKc1aoy5HpQhYCVfU8BNEryAF2hU6isrL+RB4chqIcxarxkoE5EY=
  on:
    repo: dldevinc/paper-admin
    condition: "$TRAVIS_PYTHON_VERSION = 3.8"
    tags: true
