language: python
python:
  - 3.8
  - 3.7
  - 3.6
before_install:
  - nvm install 14
  - node --version
  - pip install twine
  - pip install -U pip setuptools wheel tox-travis
  - npm i
install:
  - pip install -r ./requirements_dev.txt
  - npx webpack
branches:
  only:
    - master
    - "/^v?\\d(\\.\\d+)+$/"
script:
  - python setup.py sdist
  - python setup.py bdist_wheel
  - twine check dist/*
  - tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  user: __token__
  password:
    secure: BDy011zw9dlDgA48uEm3lY+tUQQvwSnb5ADdxYVgwYDtvn/6Q4e3AOgt3QXEnq/tpONMayeb1+UWvPXlWjKeUS0ZPt+f49E9WY1f0urZEJhrZtbeiqwRO5aMd31/MA463QtU6HlC4+LWwGbrhn8lQlPkFPXimz+g8tBzrybse0wSf/u09PlwciEX+012+W9tvR2eto2Of+Ztz+d989wunXYz7KIgYDRch4WhkmrUXO8Qq35CvbHApxl8f4P1ePZDUeSSENiecSmFRXp/ciPdfeD1/ObSAwksR24wMv1mFpRybsZMS9E3fABZt8B1lArQXoq8buUrHBNhSAGMtem4wXk4ulrZydOUYTOvjZrD0yBE/K2r8BgK48HxwGDQ2auJVjDJmBPaDTbaqW2n4IP9/S14pVpcpAYGjlBGt9DgZ/TgcsRYdH0wMneF65Y+y1mOHbq1zNIXATPq97oXJG3NKJ5az1uhAXZoQinmktUHrDeW3074RoydoYsGynKV1Xbd4yFe53bu/pDwFhGkcyaQpd53Lpd1OhdMeC8BJ7aUTdWBJFpM9OQHutPWcHnnoL2nKNKi8eybUgQiSqtDldwx509as/jbfLTVC7jnL1DdNKCI+r9D6LcOIhHQfdYgScDcPMe8NnnhzMQnVh9Rplrax3tBT8NcqQYtKmFbGXM3ZDo=
  on:
    repo: dldevinc/paper-admin
    condition: "$TRAVIS_PYTHON_VERSION = 3.8"
    tags: true
