# Generated by Django 3.2.18 on 2023-04-26 16:14

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('order', models.IntegerField(default=0, editable=False, verbose_name='order')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='position')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='sortables.company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='sortables.person')),
            ],
        ),
        migrations.CreateModel(
            name='MPTTTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('position', models.PositiveIntegerField(default=0, editable=False, verbose_name='position')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sortables.mptttree')),
            ],
            options={
                'verbose_name': 'MPTT',
                'verbose_name_plural': 'MPTT',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='DjangoTreeQueriesNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('position', models.PositiveIntegerField(default=0, editable=False, verbose_name='position')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sortables.djangotreequeriesnode', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Django Tree Queries',
                'verbose_name_plural': 'Django Tree Queries',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='CompanyIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry', to='sortables.company')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='sortables.industry')),
            ],
        ),
    ]
