# Generated by Django 2.1.15 on 2021-05-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortables', '0002_auto_20210521_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='order',
            field=models.IntegerField(default=0, editable=False, verbose_name='order'),
        ),
    ]
