# Generated by Django 3.2.6 on 2021-08-25 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sortables', '0006_auto_20210825_0616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='MPTTTree',
        ),
    ]
