# Generated by Django 3.2.6 on 2021-08-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sortables', '0009_auto_20210825_0727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mptttree',
            options={'ordering': ['position'], 'verbose_name': 'MPTT', 'verbose_name_plural': 'MPTT'},
        ),
        migrations.RenameField(
            model_name='mptttree',
            old_name='order',
            new_name='position',
        ),
    ]
