# Generated by Django 3.2.6 on 2021-08-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortables', '0010_auto_20210825_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangotreequeriesnode',
            name='position',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='mptttree',
            name='position',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='position'),
        ),
    ]
