# Generated by Django 4.0.4 on 2022-06-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortables', '0011_auto_20210825_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyindustry',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
    ]
